version: "3.8"
services:
  backend:
    image: "hassanebry/springboot-react-fullstack:11.1.2022.21.52.17"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev