version: "3.8"
services:
  backend:
    image: "hassanebry/springboot-react-fullstack:12.1.2022.10.26.48"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev